/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package wrapper;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;

/**
 *
 * @author Mike
 */
public class PlayerIconPanel extends javax.swing.JPanel {

    Player player;

    
    
    
    public PlayerIconPanel()
    {

        this(new Player("Test Player"));

    }
    
    public PlayerIconPanel(Player player) {
        initComponents();
        this.player = player;
        this.setSize(250, 50);
        this.setVisible(true);
   }
    
    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        g.translate(0, 0);
        float w = this.getWidth();
        float h = this.getHeight();
        
        this.setBackground(Color.yellow);
        
        g.drawString(player.getName(), 0, (int)h/2);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
